################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

################ Korean language ##################
[ko]
languageName = "한국어"
languageCode = "ko-kr"
contentDir = "content/korean"
