############# Korean navigation ##############

# main menu
[[main]]
name = "홈"
url = "/"
weight = 1

[[main]]
name = "블로그"
url = "/blog"
weight = 2

[[main]]
name = "프로젝트"
url = "/projects"
weight = 3

[[main]]
name = "연락처"
url = "/contact"
weight = 4 